spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: a4o9ym46nzt6ne0
        url: jdbc:mysql://localhost:3306/3vial_app_account?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        #For MySQL 8
        database-platform: org.hibernate.dialect.MySQL8Dialect
        #For MySQL 5
        #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
    security:
        user:
            name: user;
            password: user;
server:
    port: 8084
