spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: "${PASSWORD}"
        url: jdbc:mysql://localhost:3306/3vial_app?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        #For MySQL 8
        database-platform: org.hibernate.dialect.MySQL8Dialect
        #For MySQL 5
        #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true

server:
    port: 8082

arguments:
    realNordigenUrl: https://ob.nordigen.com/
    fakeNordigenUrl: http://localhost:8086/