spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: "${TRIVIAL_DB_PASSWORD}"
        url: jdbc:mysql://localhost:3306/3vial_app_source_manager?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
        defer-datasource-initialization: true
    sql:
        init:
            mode: always

server:
    port: 8087
    servlet:
        contextPath: /source_manager

arguments.source-manager:
    baseUrl: https://ob.nordigen.com
    secretId: "${TRIVIAL_NORDIGEN_SECRET_ID}"
    secretKey: "${TRIVIAL_NORDIGEN_SECRET_KEY}"
